# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a548c512852d5c9a2952fc38948ade76b8762b5963cc6a52039b756d69b9dbcf451488f1dcaad2af931317b1fdacfca8509a901e45e474c39a1f47839279198e

test:
  secret_key_base: 710dd7d4a196f3ecff10e472be3690af2138d749be0745868505500711667f02da9a291addceb42c866ba6959d23b0d4e10b760b68c6b25e1bb992f2b5b8a160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
